// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkullShakes.Api.BancoDeDados;

#nullable disable

namespace SkullShakes.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917230208_AddPedidoHistorico")]
    partial class AddPedidoHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkullShakes.Api.Modelos.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisponivel")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemPedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoId");

                    b.ToTable("Adicionais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Fruta",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Banana",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Po",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Ninho",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Fruta",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Morango",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Fruta",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Guaraná",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Po",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Paçoca",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Creme",
                            Disponivel = true,
                            IsDisponivel = true,
                            Nome = "Nutella",
                            PrecoBase = 5.00m
                        });
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Motoboy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Motoboys");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<int>("ModalidadePagamento")
                        .HasColumnType("integer");

                    b.Property<int?>("MotoboyId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PagamentoExternoId")
                        .HasColumnType("text");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("MotoboyId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.PedidoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAnterior")
                        .HasColumnType("text");

                    b.Property<string>("StatusNovo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidosHistorico");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Personalizavel")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<int>("TamanhoMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "",
                            Descricao = "Açaí puro expresso, 500ml.",
                            Disponivel = true,
                            ImagemUrl = "",
                            IsAtivo = true,
                            Nome = "SS Tradicional",
                            Personalizavel = false,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "",
                            Descricao = "Açaí, leite ninho e leite condensado. 500ml.",
                            Disponivel = true,
                            ImagemUrl = "",
                            IsAtivo = true,
                            Nome = "SS com Leite em Pó",
                            Personalizavel = false,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "",
                            Descricao = "Açaí puro. Escolha seus adicionais.",
                            Disponivel = true,
                            ImagemUrl = "",
                            IsAtivo = true,
                            Nome = "Monte o seu SS",
                            Personalizavel = true,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        });
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.StoreSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAberta")
                        .HasColumnType("boolean");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseAutoSchedule")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("StoreSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAberta = true,
                            ScheduleJson = "{}",
                            UseAutoSchedule = false
                        });
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Adicional", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.ItemPedido", null)
                        .WithMany("Adicionais")
                        .HasForeignKey("ItemPedidoId");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");

                    b.HasOne("SkullShakes.Api.Modelos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Pedido", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.Motoboy", "Motoboy")
                        .WithMany()
                        .HasForeignKey("MotoboyId");

                    b.Navigation("Motoboy");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.PedidoHistorico", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.Pedido", "Pedido")
                        .WithMany("Historico")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.RefreshToken", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.Navigation("Adicionais");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Pedido", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
