// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkullShakes.Api.BancoDeDados;

#nullable disable

namespace SkullShakes.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916164853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkullShakes.Api.Modelos.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemPedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoId");

                    b.ToTable("Adicionais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Fruta",
                            Disponivel = true,
                            Nome = "Banana",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Po",
                            Disponivel = true,
                            Nome = "Ninho",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Fruta",
                            Disponivel = true,
                            Nome = "Morango",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Fruta",
                            Disponivel = true,
                            Nome = "Guaraná",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Po",
                            Disponivel = true,
                            Nome = "Paçoca",
                            PrecoBase = 3.00m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Creme",
                            Disponivel = true,
                            Nome = "Nutella",
                            PrecoBase = 5.00m
                        });
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Personalizavel")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<int>("TamanhoMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Açaí puro expresso, 500ml.",
                            Disponivel = true,
                            Nome = "SS Tradicional",
                            Personalizavel = false,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Açaí, leite ninho e leite condensado. 500ml.",
                            Disponivel = true,
                            Nome = "SS com Leite em Pó",
                            Personalizavel = false,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Açaí puro. Escolha seus adicionais.",
                            Disponivel = true,
                            Nome = "Monte o seu SS",
                            Personalizavel = true,
                            PrecoBase = 20.00m,
                            TamanhoMl = 500
                        });
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Adicional", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.ItemPedido", null)
                        .WithMany("Adicionais")
                        .HasForeignKey("ItemPedidoId");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.HasOne("SkullShakes.Api.Modelos.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");

                    b.HasOne("SkullShakes.Api.Modelos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.ItemPedido", b =>
                {
                    b.Navigation("Adicionais");
                });

            modelBuilder.Entity("SkullShakes.Api.Modelos.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
